<?php

/**
 * ProcessWire Dimension Inputfieldtype
 * by "Soma" Philipp Urlich
 *
 * ProcessWire 2.x
 * Copyright (C) 2010 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class InputfieldDimension extends Inputfield {

    public static function getModuleInfo() {
        return array(
            'title' => __('Dimension Inputfield', __FILE__), // Module Title
            'summary' => __('Simple dimension input field.', __FILE__), // Module Summary
            'version' => 100,
            'requires' => array("FieldtypeDimension")
        );
    }

    public function __construct() {
        parent::__construct();
    }

    public function init() {
        return parent::init();
    }

    public function set($key, $value) {
        if($key == 'inputType') {
            $this->attr('type', $value);
        }
        return parent::set($key, $value);
    }

    public function setAttribute($key, $value) {
        return parent::setAttribute($key, $value);
    }

    public function ___render() {

        $out = '';
        $value = $this->attr('value');

        $label_width = $this->_("W");
        $label_height = $this->_("H");
        $label_depth = $this->_("D");

        $out .= "<div class='dimension_col'><label>{$label_width} <input type='number' style='width:{$this->inputwidth}px' name='{$this->name}_width' id='Inputfield_" . $this->name . "_width' value='" . $value->width . "'/></label></div>";
        $out .= "<div class='dimension_col'><label>{$label_height} <input type='number' style='width:{$this->inputwidth}px' name='{$this->name}_height' id='Inputfield_" . $this->name . "_height' value='" . $value->height . "'/></label></div>";
        $out .= "<div class='dimension_col'><label>{$label_depth} <input type='number' style='width:{$this->inputwidth}px' name='{$this->name}_depth' id='Inputfield_" . $this->name . "_depth' value='" . $value->depth . "'/></label></div>";

        return $out;
    }


    public function ___processInput(WireInputData $input) {

        $name = $this->attr('name');
        $dim = $this->attr('value');

        $dim_names = array(
                    'width' => $name . "_width",
                    'height' => $name . "_height",
                    'depth' => $name . "_depth"
                    );

        // loop all 2 inputs and set them if changed
        foreach($dim_names as $key => $name) {
            if(isset($input->$name)) {
                if($dim->$key != $input->$name){
                    $dim->set($key, $input->$name);
                    $this->trackChange('value');
                }
            }
        }

        return $this;
    }

}